# message types (the first identifying piece of a serialized message)
MSG_TYPE_HANDSHAKE = 1
MSG_TYPE_ANNOUNCE = 2
MSG_TYPE_PUBLISH = 3
MSG_TYPE_RPC_REQUEST = 4
MSG_TYPE_RPC_RESPONSE = 5

# service types
SERVICE_TYPE_PUBLISH = MSG_TYPE_PUBLISH
SERVICE_TYPE_RPC = MSG_TYPE_RPC_REQUEST

# error codes
RPC_ERR_NOHANDLER = 1
RPC_ERR_KNOWN = 2
RPC_ERR_UNKNOWN = 3
