# message types (the first identifying piece of a serialized message)
MSG_TYPE_HANDSHAKE = 1
MSG_TYPE_ANNOUNCE = 2
MSG_TYPE_PUBLISH = 3
MSG_TYPE_RPC_REQUEST = 4
MSG_TYPE_RPC_RESPONSE = 5
MSG_TYPE_RPC_PROXY = 6
MSG_TYPE_PROXY_PUBLISH = 7
MSG_TYPE_PROXY_REQUEST = 8
MSG_TYPE_PROXY_RESPONSE = 9
MSG_TYPE_PROXY_RESPONSE_COUNT = 10

# error codes
RPC_ERR_MALFORMED = 1
RPC_ERR_NOHANDLER = 2
RPC_ERR_KNOWN = 3
RPC_ERR_UNKNOWN = 4
RPC_PROXY_ERR_UNROUTABLE = 5
