# message types (the first identifying piece of a serialized message)
MSG_TYPE_HANDSHAKE = 1
MSG_TYPE_ANNOUNCE = 2
MSG_TYPE_UNSUBSCRIBE = 3
MSG_TYPE_PUBLISH = 4
MSG_TYPE_RPC_REQUEST = 5
MSG_TYPE_RPC_RESPONSE = 6
MSG_TYPE_PROXY_PUBLISH = 7
MSG_TYPE_PROXY_REQUEST = 8
MSG_TYPE_PROXY_RESPONSE = 9
MSG_TYPE_PROXY_RESPONSE_COUNT = 10
MSG_TYPE_PROXY_QUERY_COUNT = 11

# error codes
RPC_ERR_MALFORMED = 1
RPC_ERR_NOHANDLER = 2
RPC_ERR_NOMETHOD = 3
RPC_ERR_KNOWN = 4
RPC_ERR_UNKNOWN = 5
RPC_ERR_LOST_CONN = 6
RPC_ERR_UNSER_RESP = 7
